apiVersion: v1
kind: Service
metadata:
  name: magento-php
spec:
  selector:
    app: magento
    tier: php
  ports:
  - port: 9000
    targetPort: 9000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: install
data:
  install.sh: |
    DOMAIN=${1:-magento.test}
    echo "Composer auth for repo.magento.com"
    composer config --global http-basic.repo.magento.com 9a88e8f9040ba41a8516077e2bbad8e0 9fe89f9ee74c4bf55d6a2da335837b4a
    chown -R app:app /var/www/html/
    echo "Creat project template"
    composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.4.4 . 

    composer config --no-plugins allow-plugins.magento/magento-composer-installer true
    composer config --no-plugins allow-plugins.magento/inventory-composer-installer true
    composer config --no-plugins allow-plugins.laminas/laminas-dependency-plugin true

    bin/clinotty bin/magento setup:install \
      --db-host="$MYSQL_HOST" \
      --db-name="$MYSQL_DATABASE" \
      --db-user="$MYSQL_USER" \
      --db-password="$MYSQL_PASSWORD" \
      --base-url=https://"$DOMAIN"/ \
      --base-url-secure=https://"$DOMAIN"/ \
      --backend-frontname="$MAGENTO_ADMIN_FRONTNAME" \
      --admin-firstname="$MAGENTO_ADMIN_FIRST_NAME" \
      --admin-lastname="$MAGENTO_ADMIN_LAST_NAME" \
      --admin-email="$MAGENTO_ADMIN_EMAIL" \
      --admin-user="$MAGENTO_ADMIN_USER" \
      --admin-password="$MAGENTO_ADMIN_PASSWORD" \
      --language="$MAGENTO_LOCALE" \
      --currency="$MAGENTO_CURRENCY" \
      --timezone="$MAGENTO_TIMEZONE" \
      --amqp-host="$RABBITMQ_HOST" \
      --amqp-port="$RABBITMQ_PORT" \
      --amqp-user="$RABBITMQ_DEFAULT_USER" \
      --amqp-password="$RABBITMQ_DEFAULT_PASS" \
      --amqp-virtualhost="$RABBITMQ_DEFAULT_VHOST" \
      --cache-backend=redis \
      --cache-backend-redis-server=$REDIS_HOST \
      --cache-backend-redis-db=$REDIS_DB_CACHE_BACKEND \
      --page-cache=redis \
      --page-cache-redis-server=$REDIS_HOST \
      --page-cache-redis-db=$REDIS_DB_CACHE_FRONTEND \
      --session-save=redis \
      --session-save-redis-host=$REDIS_HOST \
      --session-save-redis-log-level=4 \
      --session-save-redis-db=$REDIS_DB_SESSION \
      --search-engine=elasticsearch7 \
      --elasticsearch-host=$ES_HOST \
      --elasticsearch-port=$ES_PORT \
      --use-rewrites=1 \
      --no-interaction

    echo "Forcing deploy of static content to speed up initial requests..."
    bin/magento setup:static-content:deploy -f

    echo "Re-indexing with Elasticsearch..."
    bin/magento indexer:reindex

    echo "Setting basic URL and generating SSL certificate..."
    bin/setup-domain "${DOMAIN}"

    echo "Fixing owner and permissions..."
    chown -R app:app /var/www/html/

    echo "Clearing the cache to apply updates..."
    bin/magento cache:flush

    echo "Installing cron, run 'bin/cron start' to enable..."
    bin/magento cron:install

    echo "Turning on developer mode..."
    bin/magento deploy:mode:set developer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: magento
data:
  MYSQL_HOST: "db"
  MYSQL_ROOT_PASSWORD: "magento"
  MYSQL_DATABASE: "magento"
  MYSQL_USER: "magento"
  MYSQL_PASSWORD: "magento"
  MYSQL_INTEGRATION_ROOT_PASSWORD: "magento"
  MYSQL_INTEGRATION_DATABASE: "magento_integration_tests"
  MYSQL_INTEGRATION_USER: "magento"
  MYSQL_INTEGRATION_PASSWORD: "magento"
  MYSQL_INTEGRATION_HOST: "db"
  ES_HOST: "elasticsearch"
  ES_PORT: "9200"
  ES_HEALTHCHECK_TIMEOUT: "100"
  MAGENTO_ADMIN_EMAIL: "john.smith@gmail.com"
  MAGENTO_ADMIN_FIRST_NAME: "john"
  MAGENTO_ADMIN_LAST_NAME: "smith"
  MAGENTO_ADMIN_USER: "john.smith"
  MAGENTO_ADMIN_PASSWORD: "password123"
  MAGENTO_ADMIN_FRONTNAME: "admin"
  MAGENTO_LOCALE: "en_US"
  MAGENTO_CURRENCY: "USD"
  MAGENTO_TIMEZONE: "America/New_York"
  BLACKFIRE_CLIENT_ID: ""
  BLACKFIRE_CLIENT_TOKEN: ""
  COMPOSER_DISABLE_XDEBUG_WARN: "1"
  PHP_CS_FIXER_IGNORE_ENV: "1"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_MANAGEMENT_PORT: "15672"
  RABBITMQ_DEFAULT_USER: "magento"
  RABBITMQ_DEFAULT_PASS: "magento"
  RABBITMQ_DEFAULT_VHOST: "/"
  RABBITMQ_HEALTHCHECK_TIMEOUT: "10"
  REDIS_HOST: "redis"
  REDIS_DB_CACHE_BACKEND: "0"
  REDIS_DB_CACHE_FRONTEND: "1"
  REDIS_DB_SESSION: "2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-php
spec:
  selector:
    matchLabels:
      app: magento
      tier: php
  template:
    metadata:
      labels:
        app: magento
      tier: php
    spec:
      containers:
      - name: magento-php
        image: caotangdaiduong/magento-php:latest
        resources:
          limits:
            memory: "725Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "bash", "/usr/bin/install.sh", "magento2.test"]