apiVersion: v1
kind: Service
metadata:
  name: magento-php
spec:
  selector:
    app: magento
    tier: php
  ports:
  - port: 9000
    targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magento-php
spec:
  selector:
    matchLabels:
      app: magento
      tier: php
  template:
    metadata:
      labels:
        app: magento
      tier: php
    spec:
      containers:
      - name: magento-php
        image: caotangdaiduong/magento-php81:latest
        resources:
          limits:
            memory: "725Mi"
            cpu: "500m"
        ports:
        - containerPort: 9000
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "composer config --global http-basic.repo.magento.com 9a88e8f9040ba41a8516077e2bbad8e0 9fe89f9ee74c4bf55d6a2da335837b4a && chown -R app:app /var/www/html/ && composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.4.4 ."]